const quotes = [
  "The only way to do great work is to love what you do.",
  "Life is what happens when you're busy making other plans.",
  "In the middle of every difficulty lies opportunity.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Do not watch the clock. Do what it does. Keep going.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Believe you can and you're halfway there.",
  "It does not matter how slowly you go as long as you do not stop.",
  "You miss 100% of the shots you don’t take.",
  "The best way to predict the future is to create it.",
  "Strive not to be a success, but rather to be of value.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "Life is 10% what happens to us and 90% how we react to it.",
  "The mind is everything. What you think you become.",
  "The only person you are destined to become is the person you decide to be.",
  "Whatever you are, be a good one.",
  "Don’t count the days, make the days count.",
  "Happiness is not something ready-made. It comes from your own actions.",
  "The secret of getting ahead is getting started.",
  "You must be the change you wish to see in the world.",
  "What you get by achieving your goals is not as important as what you become by achieving them.",
  "I can’t change the direction of the wind, but I can adjust my sails to always reach my destination.",
  "The harder I work, the luckier I get.",
  "If you want to lift yourself up, lift up someone else.",
  "The best revenge is massive success.",
  "Your time is limited, don’t waste it living someone else’s life.",
  "Whether you think you can or you think you can’t, you’re right.",
  "The two most important days in your life are the day you are born and the day you find out why.",
  "The only thing standing between you and your goal is the story you keep telling yourself.",
  "People who are crazy enough to think they can change the world are the ones who do.",
  "Failure will never overtake me if my determination to succeed is strong enough.",
  "We may encounter many defeats but we must not be defeated.",
  "Knowing is not enough; we must apply. Wishing is not enough; we must do.",
  "Imagine your life is perfect in every respect; what would it look like?",
  "We become what we think about.",
  "The man who has confidence in himself gains the confidence of others.",
  "The only place where success comes before work is in the dictionary.",
  "You are never too old to set another goal or to dream a new dream.",
  "If you’re not willing to risk the usual, you will have to settle for the ordinary.",
  "All progress takes place outside the comfort zone.",
  "The way to get started is to quit talking and begin doing.",
  "It always seems impossible until it’s done.",
  "Don’t let yesterday take up too much of today.",
  "You learn more from failure than from success. Don’t let it stop you. Failure builds character.",
  "The successful warrior is the average man, with laser-like focus.",
  "There are no limits to what you can accomplish, except the limits you place on your own thinking.",
  "The only thing worse than being blind is having sight but no vision.",
  "I find that the harder I work, the more luck I seem to have.",
  "Dream big and dare to fail.",
  "It’s not whether you get knocked down, it’s whether you get up.",
  "If you want to achieve greatness stop asking for permission.",
  "The road to success and the road to failure are almost exactly the same.",
  "The ones who are crazy enough to think they can change the world are the ones who do.",
  "Opportunities don’t happen. You create them.",
  "Don’t be afraid to give up the good to go for the great.",
  "The only person you should try to be better than is the person you were yesterday.",
  "The secret to getting ahead is getting started.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "The only real mistake is the one from which we learn nothing.",
  "The biggest risk is not taking any risk.",
  "The more you praise and celebrate your life, the more there is in life to celebrate.",
  "The best dreams happen when you’re awake.",
  "The best preparation for tomorrow is doing your best today.",
  "The only thing that stands between you and your dream is the will to try.",
  "The only true wisdom is in knowing you know nothing.",
  "The best way out is always through.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The purpose of our lives is to be happy.",
  "The journey of a thousand miles begins with one step.",
  "The only thing we have to fear is fear itself.",
  "The best and most beautiful things in the world cannot be seen or even touched—they must be felt with the heart.",
  "The best revenge is to be unlike him who performed the injury.",
  "The only way to have a friend is to be one.",
  "The best way to find yourself is to lose yourself in the service of others.",
  "The best things in life are free.",
  "The best is yet to come.",
  "The best time for new beginnings is now.",
  "The best way to predict your future is to create it.",
  "The best dreams are the ones you make come true.",
  "The best things come to those who wait.",
  "The best way to cheer yourself up is to cheer somebody else up.",
  "The best way to appreciate your job is to imagine yourself without one.",
  "The best way to gain self-confidence is to do what you are afraid to do.",
  "The best way to make your dreams come true is to wake up.",
  "The best way to find out if you can trust somebody is to trust them.",
  "The best way to escape from a problem is to solve it.",
  "The best way to predict the future is to invent it.",
  "The best way to keep your word is not to give it.",
  "The best way to get started is to quit talking and begin doing.",
  "The best way to live is to love what you do.",
  "The best way to be happy is to make others happy.",
  "The best way to succeed is to double your failure rate.",
  "The best way to make your dreams come true is to wake up and work.",
  "The best way to predict your future is to create it today.",
  "The best way to enjoy life is to work hard and play harder.",
  "The best way to find happiness is to stop searching for it.",
  "The best way to live is to leave no regrets.",
  "Success is not about luck; it’s about consistency and hard work.",
  "The only limits in life are the ones you set for yourself.",
  "Your attitude determines your direction, so choose a positive one daily.",
  "Great things never come from comfort zones—step out and take risks.",
  "Failure is just a lesson in disguise; keep moving forward.",
  "Happiness is found when you stop comparing yourself to others.",
  "The secret to getting ahead is simply getting started today.",
  "You don’t have to be perfect, just better than yesterday.",
  "Opportunities multiply when you seize them instead of waiting.",
  "Small progress every day leads to big results over time.",
  "Your life changes when you take responsibility for your choices.",
  "Confidence is silent; insecurities are loud—trust your journey.",
  "The best revenge is living well and never looking back.",
  "Dreams don’t work unless you do—put in the effort.",
  "Kindness costs nothing but can mean everything to someone.",
  "Patience is not the ability to wait but how you act while waiting.",
  "You become what you believe, so feed your mind positivity.",
  "The road to success is always under construction—keep building.",
  "Stop overthinking and start doing; action kills fear.",
  "Your vibe attracts your tribe—surround yourself with good energy.",
  "Discipline is choosing what you want most over what you want now.",
  "Be so good they can’t ignore you—master your craft.",
  "The only way to fail is to quit trying altogether.",
  "Growth begins at the end of your comfort zone—stretch yourself.",
  "Stay focused on your goals, not the noise around you.",
  "Mistakes are proof you’re trying—don’t fear them.",
  "You can’t change yesterday, but you can start today.",
  "Simplicity is the ultimate sophistication—cut the clutter in life.",
  "Courage doesn’t mean you’re fearless; it means you act despite fear.",
  "The harder you work, the luckier you become—keep grinding.",
  "Your time is limited; spend it on what truly matters.",
  "Comparison is the thief of joy—run your own race.",
  "Success is a series of small wins stacked together.",
  "Be the reason someone believes in the goodness of people.",
  "The mind is a powerful tool—train it for greatness.",
  "Every expert was once a beginner—start where you are.",
  "Gratitude turns what you have into enough—practice it daily.",
  "Consistency is the key to unlocking long-term success.",
  "You are enough, but there’s always room to grow.",
  "The best investment you can make is in yourself.",
  "Don’t wait for inspiration—create it through action.",
  "Life is short; make every moment count with purpose.",
  "Strength grows in the moments you think you can’t go on.",
  "Your habits shape your future—choose them wisely.",
  "The only approval you need is your own—be free.",
  "Turn your wounds into wisdom and your pain into power.",
  "A positive mindset brings positive outcomes—control your thoughts.",
  "The world needs your unique voice—don’t silence it.",
  "Excuses will always be there; opportunities won’t—seize them.",
  "You rise by lifting others—success is sweeter shared.",
  "Clarity comes from action, not just thought—move forward.",
  "The universe rewards courage—take that leap of faith.",
  "Progress over perfection—done is better than perfect.",
  "Your energy introduces you before you even speak—radiate goodness.",
  "Challenges are gifts that force us to grow stronger.",
  "Be stubborn about your goals but flexible about your methods.",
  "The best way to predict your future is to create it.",
  "Your struggles today are your strengths tomorrow—keep fighting.",
  "Happiness is an inside job—stop outsourcing it.",
  "Action is the bridge between dreams and reality—build it.",
  "You are the author of your life—write a great story.",
  "Fear is a liar—don’t let it write your future.",
  "Stay patient; great things take time to unfold beautifully.",
  "The fire inside you is stronger than the obstacles ahead.",
  "Every setback is a setup for a greater comeback.",
  "Be the person you needed when you were younger.",
  "Your potential is endless—don’t let doubt cap it.",
  "Simplicity breeds focus; focus breeds mastery—keep it clean.",
  "The only competition you have is the person you were yesterday.",
  "Life isn’t about finding yourself; it’s about creating yourself.",
  "Your passion is your power—let it drive you.",
  "The best time to start was yesterday; the next best is now.",
  "You can’t pour from an empty cup—take care of yourself.",
  "Doubt kills more dreams than failure ever will—ignore it.",
  "Success is liking yourself, your work, and how you do it.",
  "The quieter you become, the more you can hear wisdom.",
  "Your legacy isn’t what you take but what you leave behind.",
  "Be so busy improving yourself that you have no time to criticize others.",
  "The greatest wealth is health—invest in it daily.",
  "You attract what you are, not what you want—be better.",
  "Wisdom comes from experience; experience comes from mistakes—learn.",
  "Your environment shapes you—choose your surroundings carefully.",
  "The best apology is changed behavior—show, don’t just say.",
  "Motivation gets you started; discipline keeps you going.",
  "Your life is your message to the world—make it inspiring.",
  "The only way to grow is to embrace discomfort.",
  "Happiness isn’t a destination; it’s a way of traveling.",
  "You don’t find time for things; you make time.",
  "The greatest risk is not taking one—bet on yourself.",
  "Your words have power—use them to uplift, not destroy.",
  "Every day is a new chance to rewrite your story.",
  "The best leaders are the best listeners—learn to hear.",
  "Your struggles are part of your success story—keep going.",
  "The best way to find light is to become it.",
  "True freedom is owning your life without apologies.",
  "Your actions today define your memories tomorrow—choose wisely.",
  "The most powerful weapon on earth is the human soul on fire.",
  "You are never alone—the universe conspires to help you.",
  "The best moments happen when you step outside routine.",
  "Your life isn’t about you—it’s about who you serve.",
  "The greatest glory isn’t in never falling but in rising every time."
];

// let fun=()=>{
// let min=0;
// let max=quotes.length;
// let randomnumber=Math.floor(Math.random()*(max-min+1)+min);
// console.log(randomnumber);
// let message=document.querySelector('.text');
// message.innerText=quotes[randomnumber];
// };

// setInterval(fun,4000);

let button=document.querySelector('button');
 button.addEventListener('click',(event)=>{
  let min=0;
  let max=quotes.length;
  let randomnumber=Math.floor(Math.random()*(max-min+1)+min);
  let message=document.querySelector('.text');
  message.innerText=quotes[randomnumber];
  // console.log(event.type); // click
 // console.log(event.target); // button
 //console.log(event.clientX)  x-direction position
//  console.log(event.clientY); y-direction position
});

// button.addEventListener('mousedown')

